### PR TITLE
fix: opengraph, meta tags

### LINKED ISSUE #88: Site description is not correct in slack summary
### Operating system

Fedora 38

### Browser

Firefox

### Bug description

Pasting the website link into slack shows the following as the summary:

image

I'm reasonably sure this is not correct ;)

I took a quick peek through the site config, but couldn't see it set incorrectly anywheres, but figured you may want to be aware of this!

### Steps to reproduce

Paste the link into slack.  (Latest client being used here, FWIW.)

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hugo-sid**
# Description

This PR adds appropriate title, description, meta tags & Open graph tags for each page.

Fixes #88 

## Type of change

Please delete options that are not relevant.

- [ ] Content change (Adding content, Changing content, Fix typo)
- [ ] Style change (Change of CSS)
- [ ] Change of functionality (Add/Change functionality, e.g. new libraries)

All Submissions:

* [x] A corresponding issue exists
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [ ] Have you lint your code locally before submission?
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream modules
* [ ] All commits are signed off which certify that you created the patch and that you agree to the [Developer Certificate of Origin](https://developercertificate.org/)

### CODE REVIEW

**Review by codablock — APPROVED** [review]

**Comment by codablock** [comment]
@hugo-sid Sorry, I missed that it's in WIP and approved already :D (ignore the approve for now until you're really done)

I wonder if it's possible to have different preview images depending on the link, e.g. for each blog post a different preview image?

**Comment by hugo-sid** [comment]
@codablock , I marked this PR as draft since I noticed that the images for the `docs` section was looking odd.

I just pushed a commit to fix this.

As of now, here is how it looks:

image

Note: the open graph image for the docs section is not a fixed image. It is generated dynamically, based on the title and description of the page parameters.

**Comment by hugo-sid** [comment]
> I wonder if it's possible to have different preview images depending on the link, e.g. for each blog post a different preview image?

Thanks for the hint @codablock . I see that for the blogs section we have nice images for each blog post.
We should use them instead of the generic/default image.

image


I will implement this.

**Comment by hugo-sid** [comment]
## Summary of changes

| Page  | Opengraph (OG) preview | OG preview URL |
| ------------- | ------------- |-------------|
| Blog page  |  image  | [Preview URL](https://metatags.io/?url=https%3A%2F%2Fdeploy-preview-89--kluctl.netlify.app%2Fblog%2F2023%2F09%2F12%2Fintroducing-the-kluctl-webui%2F) |
| Home page  | image | [Preview URL](https://metatags.io/?url=https%3A%2F%2Fdeploy-preview-89--kluctl.netlify.app%2F) |
| Documentation page  | image | [Preview URL](https://metatags.io/?url=https%3A%2F%2Fdeploy-preview-89--kluctl.netlify.app%2Fdocs%2Fgitops%2F) |
| Community page | image |  [Preview URL](https://metatags.io/?url=https%3A%2F%2Fdeploy-preview-89--kluctl.netlify.app%2Fcommunity%2F) |

@codablock can you please re-review the PR?

**Review by codablock — APPROVED** [review]

**Comment by codablock** [comment]
LGTM, will merge in a few minutes

**Pull request merged**
